# These are supported funding model platforms

github: # orange-dot
patreon: # https://patreon.com/elektrokombinacijacom?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink
