/**
 * @file ek-kor.h
 * @brief ek-kor Real-Time Operating System
 *
 * Portable RTOS kernel for embedded systems.
 * Include this single header for full API access.
 *
 * Supported platforms:
 *   - STM32G474 (ARM Cortex-M4, single-core)
 *   - TC397XP (TriCore, 6-core)
 *   - Simulation (Windows/Linux host)
 *
 * Features:
 *   - EDF (Earliest Deadline First) scheduling
 *   - Per-core ready queues (no task migration)
 *   - Priority inheritance mutexes
 *   - Cross-core IPC (mailboxes, RPC)
 *   - Zero-copy buffer pools
 */

#ifndef EK_KOR_H
#define EK_KOR_H

/* Configuration (generated by CMake) */
#include <ek-kor/config.h>

/* Core types and error codes */
#include <ek-kor/types.h>

/* Hardware abstraction layer (platform implements this) */
#include <ek-kor/hal.h>

/* Kernel initialization and control */
#include <ek-kor/kernel.h>

/* EDF scheduler */
#include <ek-kor/scheduler.h>

/* Task management */
#include <ek-kor/task.h>

/* Synchronization primitives */
#include <ek-kor/sync.h>

/* Inter-process communication */
#include <ek-kor/ipc.h>

#endif /* EK_KOR_H */
